#!/usr/bin/env bash

if [[ "$SERF_TAG_AMBARI_SERVER" == "true" ]] ;then
    echo "nothing for now"
    # Start namenode that is killed by lake of kafka service
#    su -l hdfs -c "source /usr/hdp/2.2.0.0-2041/hadoop/conf/hadoop-env.sh; /usr/hdp/2.2.0.0-2041/hadoop/sbin/hadoop-daemon.sh stop namenode"
#    sleep 5
#    su -l hdfs -c "source /usr/hdp/2.2.0.0-2041/hadoop/conf/hadoop-env.sh; /usr/hdp/2.2.0.0-2041/hadoop/sbin/hadoop-daemon.sh start namenode"
#    /usr/hdp/2.2.0.0-2041/zookeeper/bin/zookeeper-server start
#    su kafka -c "/usr/hdp/2.2.0.0-2041/kafka/bin/kafka start"
#    sleep 20

#    # Starting storm
#    echo "starting storm..."
#    su -l storm -c "/usr/hdp/2.2.0.0-2041/storm/bin/storm nimbus >> /dev/null 2>&1 &"
#    su -l storm -c "/usr/hdp/2.2.0.0-2041/storm/bin/storm supervisor >> /dev/null 2>&1 &"
#    su -l storm -c "/usr/hdp/2.2.0.0-2041/storm/bin/storm ui >> /dev/null 2>&1 &"
#
#    # Starting Hbase
#    echo "starting hbase..."
#    su -l hbase -c "/usr/hdp/2.2.0.0-2041/hbase/bin/hbase-daemon.sh start master"
#    sleep 10
#    su -l hbase -c "/usr/hdp/2.2.0.0-2041/hbase/bin/hbase-daemon.sh start regionserver"

fi

